baseURL = 'https://tellmesomething.uk/'
languageCode = 'en-us'
title = 'TMS'

  [[menu.main]]
  name = "pulse frames"
  url = "/articles/pulseframes/"
  weight = 3

      [[menu.main]]
  name = "studio"
  url = "/articles/studio/"
  weight = 2

      [[menu.main]]
  name = "development"
  url = "/articles/development/"
  weight = 1

  [[menu.main]]
  name = "case studies"
  url = "/articles/casestudies/"
  weight = 4











